#! /usr/bin/bash

dir=`dirname "$0"`
cd "$dir"
vers=""
while [ $# -gt 0 ]; do
    if [ "$1" = "-h" -o "$1" = "--help" ]; then
        prog=$(basename "$0")
        echo "usage: $prog [-h|--help] [version ...]"
        exit 0
    fi
    vers="${vers:+$vers }$1"
    shift
done
vers="${vers:=$(echo 1.{0..11})}"

for ver in $vers; do
    echo "########################################### Julia version $ver"
    rm -f Manifest.toml
    test -r ".Manifest-$ver.toml" && cp -pf ".Manifest-$ver.toml" Manifest.toml
    julia +$ver --color=yes --check-bounds=yes --depwarn=yes --project -e "
        using Pkg;
        Pkg.instantiate(); # or Pkg.resolve();
        Pkg.test();"
    test -r Manifest.toml && mv -f Manifest.toml ".Manifest-$ver.toml"
done
